#!/usr/bin/env python3
__version__ = "1.0.1"
__author__ = "Kaisar Zu"

import argparse
import logging
import os
import sys

from yowsupx.config import (AppNotInstalledException, ExportConfigException,
                            NoRootException, extracter)

ERROR_UNKNOWN = 1
ERROR_NO_ROOT = 11
ERROR_APP_NOT_INSTALLED = 12
ERROR_EXPORT_CONFIG = 13

logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(prog='yowsup-config-extract', description='Extract config from rooted android device for yowsup project.')
    options = parser.add_argument_group("Extracter options")
    options.add_argument('-s', '--serial', help='extract from specific device')
    options.add_argument('-D', '--datadir', help='extract from specific local directory')
    parser.add_argument('-p', '--package', default='com.whatsapp', help='for mod package default:com.whatsapp')
    parser.add_argument('-o', '--out', default=os.getcwd(), help='specific save directory')
    parser.add_argument('-d', '--debug', action="store_true", help='show debug log')
    args = parser.parse_args()
    ERROR_MAP = {
        NoRootException.__name__: ERROR_NO_ROOT,
        AppNotInstalledException.__name__: ERROR_APP_NOT_INSTALLED,
        ExportConfigException.__name__: ERROR_EXPORT_CONFIG,
    }
    try:
        extracter.setLogLevel(logging.DEBUG if args.debug else logging.INFO)
        if args.datadir:
            extracter.fromDirectory(args.datadir, args.serial, args.package, args.out)
        else:
            extracter.fromDevice(args.serial, args.package, args.out)
    except Exception as e:
        logging.error(e)
        if e.__class__.__name__ in ERROR_MAP:
            code = ERROR_MAP.get(e.__class__.__name__)
            sys.exit(code)
        else:
            sys.exit(ERROR_UNKNOWN)


if __name__ == '__main__':
    main()
